version: '3'
services:
  silentfeline:
    build:
      context: .
    working_dir: /home/silentfeline
    container_name: silentfeline
    restart: always
    ports:
      - "27543:27543"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1