version: '3'
services:
  adamaspcap:
    build:
      context: .
    working_dir: /home/adamaspcap
    container_name: adamaspcap
    restart: always
    ports:
      - "27545:27545"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1